package com.erp.model;
// Generated Sep 28, 2016 10:26:35 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BasePersonalImport generated by hbm2java
 */
@Entity
@Table(name = "BASE_PERSONAL_IMPORT")
public class BasePersonalImport implements java.io.Serializable {

	private String dataId;
	private String customerId;
	private String name;
	private String gender;
	private String certType;
	private String certNo;
	private String country;
	private String regionId;
	private String mobileNo;
	private String phoneNo;
	private String corpId;
	private String corpName;
	private String isSchool;
	private String class_;
	private String bankId;
	private Date insertDate;
	private String dealState;
	private String dealMsg;
	private Long lineNum;
	private String taskId;
	private String taskName;
	private String recvBrchId;
	private String applyType;
	private Long dealNo;
	private String note;

	public BasePersonalImport() {
	}

	public BasePersonalImport(String dataId, String applyType) {
		this.dataId = dataId;
		this.applyType = applyType;
	}

	public BasePersonalImport(String dataId, String customerId, String name, String gender, String certType,
			String certNo, String country, String regionId, String mobileNo, String phoneNo, String corpId,
			String corpName, String isSchool, String class_, String bankId, Date insertDate, String dealState,
			String dealMsg, Long lineNum, String taskId, String taskName, String recvBrchId, String applyType,
			Long dealNo, String note) {
		this.dataId = dataId;
		this.customerId = customerId;
		this.name = name;
		this.gender = gender;
		this.certType = certType;
		this.certNo = certNo;
		this.country = country;
		this.regionId = regionId;
		this.mobileNo = mobileNo;
		this.phoneNo = phoneNo;
		this.corpId = corpId;
		this.corpName = corpName;
		this.isSchool = isSchool;
		this.class_ = class_;
		this.bankId = bankId;
		this.insertDate = insertDate;
		this.dealState = dealState;
		this.dealMsg = dealMsg;
		this.lineNum = lineNum;
		this.taskId = taskId;
		this.taskName = taskName;
		this.recvBrchId = recvBrchId;
		this.applyType = applyType;
		this.dealNo = dealNo;
		this.note = note;
	}

	@Id

	@Column(name = "DATA_ID", unique = true, nullable = false, length = 20)
	public String getDataId() {
		return this.dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	@Column(name = "CUSTOMER_ID", length = 10)
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "GENDER", length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "CERT_TYPE", length = 20)
	public String getCertType() {
		return this.certType;
	}

	public void setCertType(String certType) {
		this.certType = certType;
	}

	@Column(name = "CERT_NO", length = 36)
	public String getCertNo() {
		return this.certNo;
	}

	public void setCertNo(String certNo) {
		this.certNo = certNo;
	}

	@Column(name = "COUNTRY", length = 20)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "REGION_ID", length = 8)
	public String getRegionId() {
		return this.regionId;
	}

	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}

	@Column(name = "MOBILE_NO", length = 13)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "PHONE_NO", length = 22)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "CORP_ID", length = 10)
	public String getCorpId() {
		return this.corpId;
	}

	public void setCorpId(String corpId) {
		this.corpId = corpId;
	}

	@Column(name = "CORP_NAME", length = 20)
	public String getCorpName() {
		return this.corpName;
	}

	public void setCorpName(String corpName) {
		this.corpName = corpName;
	}

	@Column(name = "IS_SCHOOL", length = 1)
	public String getIsSchool() {
		return this.isSchool;
	}

	public void setIsSchool(String isSchool) {
		this.isSchool = isSchool;
	}

	@Column(name = "CLASS", length = 50)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "BANK_ID", length = 50)
	public String getBankId() {
		return this.bankId;
	}

	public void setBankId(String bankId) {
		this.bankId = bankId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATE", length = 7)
	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	@Column(name = "DEAL_STATE", length = 2)
	public String getDealState() {
		return this.dealState;
	}

	public void setDealState(String dealState) {
		this.dealState = dealState;
	}

	@Column(name = "DEAL_MSG", length = 200)
	public String getDealMsg() {
		return this.dealMsg;
	}

	public void setDealMsg(String dealMsg) {
		this.dealMsg = dealMsg;
	}

	@Column(name = "LINE_NUM", precision = 38, scale = 0)
	public Long getLineNum() {
		return this.lineNum;
	}

	public void setLineNum(Long lineNum) {
		this.lineNum = lineNum;
	}

	@Column(name = "TASK_ID", length = 20)
	public String getTaskId() {
		return this.taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	@Column(name = "TASK_NAME", length = 100)
	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "RECV_BRCH_ID", length = 20)
	public String getRecvBrchId() {
		return this.recvBrchId;
	}

	public void setRecvBrchId(String recvBrchId) {
		this.recvBrchId = recvBrchId;
	}

	@Column(name = "APPLY_TYPE", nullable = false, length = 1)
	public String getApplyType() {
		return this.applyType;
	}

	public void setApplyType(String applyType) {
		this.applyType = applyType;
	}

	@Column(name = "DEAL_NO", precision = 38, scale = 0)
	public Long getDealNo() {
		return this.dealNo;
	}

	public void setDealNo(Long dealNo) {
		this.dealNo = dealNo;
	}

	@Column(name = "NOTE", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dataId == null) ? 0 : dataId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BasePersonalImport other = (BasePersonalImport) obj;
		if (dataId == null) {
			if (other.dataId != null)
				return false;
		} else if (!dataId.equals(other.dataId))
			return false;
		return true;
	}
}
