package com.erp.model;
// Generated Sep 28, 2016 10:26:35 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BasePersonalImportBatch generated by hbm2java
 */
@Entity
@Table(name = "BASE_PERSONAL_IMPORT_BATCH")
public class BasePersonalImportBatch implements java.io.Serializable {

	private Long dealNo;
	private Date insertDate;
	private Long totNums;
	private Long sucNums;
	private Long errNums;
	private Long newApplyNums;
	private Long hfApplyNums;
	private Long applyNums;
	private Long notApplyNums;
	private String orgId;
	private String brchId;
	private String userId;
	private String note;
	private String state;

	public BasePersonalImportBatch() {
	}

	public BasePersonalImportBatch(Long dealNo) {
		this.dealNo = dealNo;
	}

	public BasePersonalImportBatch(Long dealNo, Date insertDate, Long totNums, Long sucNums,
			Long errNums, Long newApplyNums, Long hfApplyNums, Long applyNums,
			Long notApplyNums, String orgId, String brchId, String userId, String note, String state) {
		this.dealNo = dealNo;
		this.insertDate = insertDate;
		this.totNums = totNums;
		this.sucNums = sucNums;
		this.errNums = errNums;
		this.newApplyNums = newApplyNums;
		this.hfApplyNums = hfApplyNums;
		this.applyNums = applyNums;
		this.notApplyNums = notApplyNums;
		this.orgId = orgId;
		this.brchId = brchId;
		this.userId = userId;
		this.note = note;
		this.state = state;
	}

	@Id

	@Column(name = "DEAL_NO", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getDealNo() {
		return this.dealNo;
	}

	public void setDealNo(Long dealNo) {
		this.dealNo = dealNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATE", length = 7)
	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	@Column(name = "TOT_NUMS", precision = 38, scale = 0)
	public Long getTotNums() {
		return this.totNums;
	}

	public void setTotNums(Long totNums) {
		this.totNums = totNums;
	}

	@Column(name = "SUC_NUMS", precision = 38, scale = 0)
	public Long getSucNums() {
		return this.sucNums;
	}

	public void setSucNums(Long sucNums) {
		this.sucNums = sucNums;
	}

	@Column(name = "ERR_NUMS", precision = 38, scale = 0)
	public Long getErrNums() {
		return this.errNums;
	}

	public void setErrNums(Long errNums) {
		this.errNums = errNums;
	}

	@Column(name = "NEW_APPLY_NUMS", precision = 38, scale = 0)
	public Long getNewApplyNums() {
		return this.newApplyNums;
	}

	public void setNewApplyNums(Long newApplyNums) {
		this.newApplyNums = newApplyNums;
	}

	@Column(name = "HF_APPLY_NUMS", precision = 38, scale = 0)
	public Long getHfApplyNums() {
		return this.hfApplyNums;
	}

	public void setHfApplyNums(Long hfApplyNums) {
		this.hfApplyNums = hfApplyNums;
	}

	@Column(name = "APPLY_NUMS", precision = 38, scale = 0)
	public Long getApplyNums() {
		return this.applyNums;
	}

	public void setApplyNums(Long applyNum) {
		this.applyNums = applyNum;
	}

	@Column(name = "NOT_APPLY_NUMS", precision = 38, scale = 0)
	public Long getNotApplyNums() {
		return this.notApplyNums;
	}

	public void setNotApplyNums(Long notApplyNums) {
		this.notApplyNums = notApplyNums;
	}

	@Column(name = "ORG_ID", length = 4)
	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	@Column(name = "BRCH_ID", length = 16)
	public String getBrchId() {
		return this.brchId;
	}

	public void setBrchId(String brchId) {
		this.brchId = brchId;
	}

	@Column(name = "USER_ID", length = 8)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "NOTE", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "STATE", length = 1)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dealNo == null) ? 0 : dealNo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BasePersonalImportBatch other = (BasePersonalImportBatch) obj;
		if (dealNo == null) {
			if (other.dealNo != null)
				return false;
		} else if (!dealNo.equals(other.dealNo))
			return false;
		return true;
	}
}
