package com.erp.model;
// Generated 2016-11-7 14:22:16 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CardFjmkSaleList generated by hbm2java
 */
@Entity
@Table(name = "CARD_FJMK_SALE_LIST")
public class CardFjmkSaleList implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long dataSeq;
	private String makeBatchId;
	private String taskId;
	private String cardId;
	private String cardNo;
	private String cardType;
	private Long saleCostFee;
	private Long saleForegift;
	private String saleManager;
	private String saleToCorpId;
	private String saleToCorpName;
	private String saleState;
	private String saleUserId;
	private String saleBrchId;
	private Long dealNo;
	private String note;
	private String parentCardType;
	private String childCardType;

	public CardFjmkSaleList() {
	}

	public CardFjmkSaleList(Long dataSeq) {
		this.dataSeq = dataSeq;
	}

	public CardFjmkSaleList(Long dataSeq, String makeBatchId, String taskId, String cardId, String cardNo,
			String cardType, Long saleCostFee, Long saleForegift, String saleManager, String saleToCorpId,
			String saleToCorpName, String saleState, String saleUserId, String saleBrchId, Long dealNo,
			String note, String parentCardType, String childCardType) {
		this.dataSeq = dataSeq;
		this.makeBatchId = makeBatchId;
		this.taskId = taskId;
		this.cardId = cardId;
		this.cardNo = cardNo;
		this.cardType = cardType;
		this.saleCostFee = saleCostFee;
		this.saleForegift = saleForegift;
		this.saleManager = saleManager;
		this.saleToCorpId = saleToCorpId;
		this.saleToCorpName = saleToCorpName;
		this.saleState = saleState;
		this.saleUserId = saleUserId;
		this.saleBrchId = saleBrchId;
		this.dealNo = dealNo;
		this.note = note;
		this.parentCardType = parentCardType;
		this.childCardType = childCardType;
	}
	@Id
	@Column(name = "DATA_SEQ", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getDataSeq() {
		return this.dataSeq;
	}

	public void setDataSeq(Long dataSeq) {
		this.dataSeq = dataSeq;
	}

	@Column(name = "MAKE_BATCH_ID", length = 10)
	public String getMakeBatchId() {
		return this.makeBatchId;
	}

	public void setMakeBatchId(String makeBatchId) {
		this.makeBatchId = makeBatchId;
	}

	@Column(name = "TASK_ID", length = 18)
	public String getTaskId() {
		return this.taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	@Column(name = "CARD_ID", length = 50)
	public String getCardId() {
		return this.cardId;
	}

	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	@Column(name = "CARD_NO", length = 20)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "CARD_TYPE", length = 3)
	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	@Column(name = "SALE_COST_FEE", precision = 10, scale = 0)
	public Long getSaleCostFee() {
		return this.saleCostFee;
	}

	public void setSaleCostFee(Long saleCostFee) {
		this.saleCostFee = saleCostFee;
	}

	@Column(name = "SALE_FOREGIFT", precision = 10, scale = 0)
	public Long getSaleForegift() {
		return this.saleForegift;
	}

	public void setSaleForegift(Long saleForegift) {
		this.saleForegift = saleForegift;
	}

	@Column(name = "SALE_MANAGER", length = 100)
	public String getSaleManager() {
		return this.saleManager;
	}

	public void setSaleManager(String saleManager) {
		this.saleManager = saleManager;
	}

	@Column(name = "SALE_TO_CORP_ID", length = 100)
	public String getSaleToCorpId() {
		return this.saleToCorpId;
	}

	public void setSaleToCorpId(String saleToCorpId) {
		this.saleToCorpId = saleToCorpId;
	}

	@Column(name = "SALE_TO_CORP_NAME", length = 200)
	public String getSaleToCorpName() {
		return this.saleToCorpName;
	}

	public void setSaleToCorpName(String saleToCorpName) {
		this.saleToCorpName = saleToCorpName;
	}

	@Column(name = "SALE_STATE", length = 2)
	public String getSaleState() {
		return this.saleState;
	}

	public void setSaleState(String saleState) {
		this.saleState = saleState;
	}

	@Column(name = "SALE_USER_ID", length = 20)
	public String getSaleUserId() {
		return this.saleUserId;
	}

	public void setSaleUserId(String saleUserId) {
		this.saleUserId = saleUserId;
	}

	@Column(name = "SALE_BRCH_ID", length = 20)
	public String getSaleBrchId() {
		return this.saleBrchId;
	}

	public void setSaleBrchId(String saleBrchId) {
		this.saleBrchId = saleBrchId;
	}

	@Column(name = "DEAL_NO", precision = 38, scale = 0)
	public Long getDealNo() {
		return this.dealNo;
	}

	public void setDealNo(Long dealNo) {
		this.dealNo = dealNo;
	}

	@Column(name = "NOTE", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "PARENT_CARD_TYPE", length = 20)
	public String getParentCardType() {
		return this.parentCardType;
	}

	public void setParentCardType(String parentCardType) {
		this.parentCardType = parentCardType;
	}

	@Column(name = "CHILD_CARD_TYPE", length = 20)
	public String getChildCardType() {
		return this.childCardType;
	}

	public void setChildCardType(String childCardType) {
		this.childCardType = childCardType;
	}

}
