UPDATE SYS_CODE
   SET CODE_STATE = '1'
 WHERE CODE_TYPE = 'CANCEL_REASON'
   AND CODE_VALUE IN ('1', '2', '3', '4');

INSERT INTO SYS_CODE
  (CODE_TYPE,
   TYPE_NAME,
   CODE_VALUE,
   CODE_NAME,
   CODE_STATE,
   ORD_NO,
   FIELD_NAME)
VALUES
  ('CANCEL_REASON', '注销原因', '5', '社保转移退卡', '0', 5, 'SBZYTK');

INSERT INTO SYS_CODE
  (CODE_TYPE,
   TYPE_NAME,
   CODE_VALUE,
   CODE_NAME,
   CODE_STATE,
   ORD_NO,
   FIELD_NAME)
VALUES
  ('CANCEL_REASON', '注销原因', '6', '其他', '0', 6, 'QT');
